
SELECT * FROM book_table;

SELECT BID, IMAGE, TITLE, AUTHOR,TRANSLATOR, PRICE, DELIVERY_FEE, ESTIMATED_DELIVERY_DATE 
FROM book_table 
WHERE BID = 1;

SELECT * FROM MEMBER_TBL;
SELECT * FROM AUTHOR_TBL;


