
SELECT * FROM book_table;

SELECT BID, IMAGE, TITLE, AUTHOR,TRANSLATOR, PRICE, DELIVERY_FEE, ESTIMATED_DELIVERY_DATE 
FROM book_table 
WHERE BID = 1;

SELECT * FROM MEMBER_TBL;
SELECT * FROM AUTHOR_TBL;

SELECT * FROM BOOK_TBL;

DELETE FROM MEMBER_TBL WHERE id = 12

UPDATE MEMBER_TBL SET MEMBER_STATE_ID = 1 WHERE ID = ?

SELECT  * FROM MEMBER_TBL WHERE id = 1;

