-- 모든 테이블 삭제
-- 만약 삭제가 안된다면 부모까지 삭제해주는 삭제 옵션 추가 -> CASCADE CONSTRAINTS
DROP TABLE BOOK_CATEGORY_TBL CASCADE CONSTRAINTS;
DROP TABLE BOOK_REVIEW_TBL;
DROP TABLE LOCKER_TBL;
DROP TABLE NOTICE_TBL;
DROP TABLE PAYMENT_TBL;
DROP TABLE BOOK_TBL;
DROP TABLE AUTHOR_TBL;
DROP TABLE ADMIN_TBL;
DROP TABLE INQUIRY_TBL;
DROP TABLE MEMBER_STATE_TBL;
DROP TABLE MEMBER_TBL;

DROP SEQUENCE book_category_SEQ;
DROP SEQUENCE BOOK_REVIEW_SEQ;
DROP SEQUENCE BOOK_SEQ;
DROP SEQUENCE MEMBER_SEQ;

-- 모든 테이블 생성 가이드
-- 1. book_categroy, member_state
-- 2. member
-- 3. author, inquiry, notice, admin
-- 4. book
-- 5. book_review, payment, locker

